name: "gcloud Setup and deploy action"
description: "Setup docker auth and kubernetes auth and deploy via skaffold"
inputs:
  service_account_key:
    description: "Google Service Key"
    required: true
    default: ""
  project:
    description: "Google Project"
    required: true
  zone:
    description: "Google Zone"
    required: true
  cluster:
    description: "Google Kubernetes Cluster *required if you are deploying"
    required: false
  skaffold_project:
    description: "The Skaffold project to use (prodcution/dev etc) *required if you are deploying"
    required: false
runs:
  using: "composite"
  steps:
    - name: Authenticate with Google Cloud
      shell: bash
      run: |
        echo ${{ inputs.service_account_key }} | base64 -d > /tmp/key.json
        gcloud auth activate-service-account --key-file=/tmp/key.json

    - name: Configure project and region
      shell: bash
      run: |
        gcloud --quiet config set project ${{ inputs.project }}
        gcloud --quiet config set compute/zone ${{ inputs.zone }}

    - name: Docker Login
      shell: bash
      run: |
        gcloud beta auth configure-docker europe-docker.pkg.dev --quiet

    - name: Get Cluster Credentials
      shell: bash
      run: |
        if [ -n "${{ inputs.cluster }}" ]; then gcloud container clusters get-credentials ${{ inputs.cluster }} --zone=${{ inputs.zone }} fi

    - name: Skaffold build and deploy ${{ inputs.skaffold_project }}
      shell: bash
      run: |
        if [ -n "${{ inputs.skaffold_project }}" ]; then skaffold run -p ${{ inputs.skaffold_project }} fi
